<h1>Numpy Basics</h1>
<h6>Saket Tiwari</h6>
Date: 14 June 2019

In [2]:
import numpy as np

In [2]:
a=np.arange(1,5,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c=np.arange(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
c.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
c.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#python list pass hua h..jisko array me convert kiya h
b=np.array([-1,0,1,100])
b

array([ -1,   0,   1, 100])

In [18]:
a=np.array([1,2,3])
a=a*2
a

array([2, 4, 6])

In [20]:
a=np.array([-1,0,1.5,100],dtype='int8')
a=a*2
a
#since it cworks on C therefore all the data is converted into floating vALUE as in C data type must be same
#due to data overflow data changes to -56 as minimum data in int8(8 bit integer)=-128 and maxm=127(range is from 0-127)

array([ -2,   0,   2, -56], dtype=int8)

In [21]:
a[2:5]

array([  2, -56], dtype=int8)

In [22]:
a[::-1]

array([-56,   2,   0,  -2], dtype=int8)

In [23]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [25]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [26]:
a=a.reshape(3,4)
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [29]:
a[1:3, -1]

array([ 7, 11])

In [31]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [32]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
c[1,1,1]

17

In [34]:
c[1,,]

SyntaxError: invalid syntax (<ipython-input-34-291fceec7f96>, line 1)

In [35]:
c[1:,:,:]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Vectorization

#Vectorization

##Vectorization

In [39]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [42]:
#numpy is a vectorized library
b*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [44]:
a**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [45]:
b**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [46]:
a>6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True])

In [48]:
a=np.arange(12)
b=np.arange(12)

In [49]:
a*b

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [50]:
a.reshape(3,4)*b.reshape(3,4)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [51]:
a.dot(b)

506

In [54]:
a.shape

(12,)

In [55]:
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [56]:
A=a.reshape(1,12)

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
A


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [61]:
B=b.reshape(1,12)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [63]:
B.T

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [66]:
A.dot(B.T)

array([[506]])

In [67]:
B.T.dot(A)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121]])

# Masking

In [68]:
a=np.arange(30)

In [69]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [70]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
a[a>15].reshape(7,2)

array([[16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [73]:
a=np.arange(12)
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [75]:
b=a.reshape(3,4)
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [80]:
c=a[:5]
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [81]:
a[0]=100

In [82]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [83]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [84]:
c

array([100,   1,   2,   3,   4])

In [85]:
#a orignally makes the data and specifications of a is written in a header
#if we create b by changing specificcations of a, only another header is formed without changing of orignal data
#if there is any change in a made aftr, change in b is automatic

In [86]:
a[a>15]
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [87]:
#only in masking the new data is formed

In [88]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [94]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Special Arrays

In [96]:
a=np.zeros((3,4),dtype='int8')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [99]:
b=np.ones((3,4),dtype='int32')*5
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [101]:
np.empty((4,5))


array([[ 4.67296746e-307,  1.69121096e-306,  1.37962320e-306,
         1.69121231e-306,  7.56599807e-307],
       [ 6.89813979e-307,  9.34603679e-307,  1.11256817e-306,
         1.06811422e-306,  1.42417221e-306],
       [ 1.11260619e-306,  8.90094053e-307,  1.86919378e-306,
         1.06809792e-306,  1.37962456e-306],
       [ 1.69111861e-306,  1.78020169e-306,  1.37961777e-306,
         7.56599807e-307, -4.20583537e-294]])

In [102]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [104]:
np.linspace(1,5,7)
#creates 7 equal spaced no b/w 1 & 5

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

# Analysis

In [105]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a.max()

11

In [112]:
np.max(b,axis=0)

array([ 8,  9, 10, 11])

In [113]:
np.max(b,axis=1)

array([ 3,  7, 11])

In [117]:
np.sum(b,axis=0)

array([12, 15, 18, 21])

In [118]:
np.sum(b,axis=1)

array([ 6, 22, 38])

In [119]:
np.mean(b)

5.5

In [120]:
np.mean(b,axis=0)

array([4., 5., 6., 7.])

In [121]:
np.mean(b,axis=1)

array([1.5, 5.5, 9.5])

In [125]:
np.median(b,axis=1)

array([1.5, 5.5, 9.5])

In [126]:
np.std(b)

3.452052529534663

In [127]:
np.std(b,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [128]:
np.std(b,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

# Distributions &Randoms

In [135]:
s=90+ np.random.rand(4,3) *10
s

array([[95.85640251, 95.84495647, 92.191972  ],
       [95.55164837, 94.734263  , 92.67860771],
       [93.99616036, 96.1587187 , 93.55041414],
       [96.05273865, 91.53065394, 92.09074778]])

In [137]:
s.astype('int8')

array([[95, 95, 92],
       [95, 94, 92],
       [93, 96, 93],
       [96, 91, 92]], dtype=int8)

In [138]:
import time

In [142]:
ticks=time.time()
ticks #Epoch time
#it is the time from 1st january 1973
#it is time zone independent
#random numbers can be generated using epoch time--> the input time which enters into the random function is called Seed

1559721729.570575

In [150]:
np.random.seed(100)
print(np.random.rand(1))
print(np.random.rand(1))
print(np.random.rand(1))

[0.54340494]
[0.27836939]
[0.42451759]


In [147]:
np.random.rand(1)

array([0.42451759])

In [151]:
np.random.seed(100)
print(np.random.rand(1))
print(np.random.rand(1))
print(np.random.rand(1))

[0.54340494]
[0.27836939]
[0.42451759]


In [5]:
np.random.randint(50,60,5)

array([59, 52, 54, 55, 54])

In [160]:
mu=100
sigma=15
s=np.random.normal(mu,sigma, 1000)
s

array([135.50433995,  96.48162264,  99.9520874 ,  87.5131928 ,
        73.44477766,  91.50393983, 114.76923602,  99.59651229,
        66.17847507, 101.80183146, 104.16836846, 107.71745572,
        80.77567381, 111.24553745, 106.06376823,  91.48376896,
        82.95847994, 103.18933099,  83.79672458, 105.65211846,
       109.97275017, 112.51566476, 104.11346599, 116.5002579 ,
       100.57567627,  85.04107813, 104.66288088,  92.47865826,
       111.82895318,  79.7377661 ,  99.54857654,  96.29601261,
        95.26726068, 119.45513612,  94.29322164, 104.58798608,
       114.93414689, 115.7010118 ,  85.55926371,  99.90935588,
       134.75893312, 103.85561032,  74.07302251, 101.91923049,
       103.61552382,  93.20225905,  91.71773357,  82.27480182,
       105.87466201, 104.28117369,  87.75385346,  93.09239601,
       105.75847882, 103.3274661 ,  90.78051533,  99.44635164,
       102.30956958,  92.51919327, 110.68302492, 114.95863347,
        94.16275441,  90.51434645, 124.81443395, 120.91

In [161]:
len(s[s>90])

741

In [162]:
len(s)

1000

In [164]:
np.mean(s)

99.81396129164277

In [165]:
np.std(s)

14.799245694711043